/// WASM Component executor.
///
/// Loads a WASM component and calls its exported transform function.
///
/// Standard Rust pipelines (configurable-transform world) use static
/// host-side bindings generated by wasmtime::component::bindgen!().  This
/// lowers list<u8> crossing the component boundary to a single memcpy per
/// call instead of per-byte Val::U8 heap allocations, which was the dominant
/// latency cost for large tensors.
///
/// Legacy componentize-py components (transform world, no init export) fall
/// back to the original dynamic Val API — they are deprecated and rare.
use anyhow::{Context, Result};
use wasmtime::{
    component::{Component, Func, Linker, Val},
    Config, Engine, Store,
};
use wasmtime_wasi::{ResourceTable, WasiCtx, WasiCtxBuilder, WasiView};

// Static host-side bindings for the standard Rust pipeline.
// Generated at compile time from the WIT definition; list<u8> params/returns
// become &[u8] / Vec<u8> with memcpy semantics inside the generated code.
mod bindings {
    wasmtime::component::bindgen!({
        world: "configurable-transform",
        path: "../../crates/transforms/wit/transform.wit",
    });
}

struct State {
    ctx: WasiCtx,
    table: ResourceTable,
}

impl WasiView for State {
    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.ctx
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

enum Inner {
    /// Standard Rust pipeline — static bindgen, one memcpy per boundary crossing.
    Standard(bindings::ConfigurableTransform),
    /// Legacy componentize-py component — dynamic Val API (deprecated).
    Legacy(Func),
}

pub struct WasmTransform {
    store: Store<State>,
    inner: Inner,
}

impl WasmTransform {
    /// Create a wasmtime Engine configured for WASM component use.
    ///
    /// Cranelift optimisations are disabled: 41 MB componentize-py components
    /// take several minutes to JIT at O2; None brings that down to seconds.
    /// Callers building multiple transforms should call this once and pass the
    /// result to each `WasmTransform::new` call, sharing the JIT resources.
    pub fn build_engine() -> Result<Engine> {
        let mut cfg = Config::new();
        cfg.wasm_component_model(true);
        cfg.cranelift_opt_level(wasmtime::OptLevel::None);
        Engine::new(&cfg).context("failed to create wasmtime engine")
    }

    /// Build a transform from raw WASM bytes using an already-created Engine.
    ///
    /// `config` is `Some` for standard Rust pipelines (triggers `init`) and
    /// `None` for legacy componentize-py components.
    pub fn new(engine: &Engine, wasm_bytes: &[u8], config: Option<&[u8]>) -> Result<Self> {
        let component =
            Component::new(engine, wasm_bytes).context("failed to compile WASM component")?;

        let mut linker: Linker<State> = Linker::new(engine);
        wasmtime_wasi::add_to_linker_sync(&mut linker)
            .context("failed to add WASI to component linker")?;

        let state = State {
            ctx: WasiCtxBuilder::new()
                .inherit_stdout()
                .inherit_stderr()
                .build(),
            table: ResourceTable::new(),
        };
        let mut store = Store::new(engine, state);

        let inner = if let Some(cfg_bytes) = config {
            // Standard Rust pipeline: static bindings give us a memcpy boundary.
            let component_bindings =
                bindings::ConfigurableTransform::instantiate(&mut store, &component, &linker)
                    .context("failed to instantiate standard WASM component")?;

            component_bindings
                .call_init(&mut store, cfg_bytes)
                .context("init call failed")?;

            Inner::Standard(component_bindings)
        } else {
            // Legacy componentize-py: keep the dynamic path untouched.
            let instance = linker
                .instantiate(&mut store, &component)
                .context("failed to instantiate legacy WASM component")?;
            let func = instance
                .get_func(&mut store, "transform")
                .context("component missing export: transform(list<u8>) -> list<u8>")?;
            Inner::Legacy(func)
        };

        Ok(Self { store, inner })
    }

    pub fn run(&mut self, input: &[u8]) -> Result<Vec<u8>> {
        let WasmTransform { store, inner } = self;
        match inner {
            Inner::Standard(b) => b.call_transform(&mut *store, input),
            Inner::Legacy(func) => run_legacy(func, &mut *store, input),
        }
        .context("transform call failed")
    }
}

/// Dynamic Val-based invocation for legacy componentize-py components.
/// Kept isolated so the hot path (standard) stays clean.
fn run_legacy(func: &Func, store: &mut Store<State>, input: &[u8]) -> Result<Vec<u8>> {
    let input_val = Val::List(input.iter().map(|&b| Val::U8(b)).collect());
    let mut results = vec![Val::Bool(false)];

    func.call(&mut *store, &[input_val], &mut results)
        .context("transform call failed")?;
    func.post_return(store).context("post_return failed")?;

    match results.remove(0) {
        Val::List(items) => {
            let mut bytes = Vec::with_capacity(items.len());
            for v in items {
                match v {
                    Val::U8(b) => bytes.push(b),
                    other => anyhow::bail!("expected u8 in result list, got {other:?}"),
                }
            }
            Ok(bytes)
        }
        other => anyhow::bail!("expected list<u8> from transform, got {other:?}"),
    }
}
